name = "clip-downloader"
main = "build/worker/shim.mjs"
compatibility_date = "2023-03-22"
usage_model = "bundled"

routes = [
    { pattern = "www.fitti.io",  custom_domain = true },
    { pattern = "clips.fitti.io",  custom_domain = true }
]

[build]
command = "cargo install -q worker-build && worker-build --release"

[env.production]
routes = [
	{ pattern = "clips.fitti.io/*", zone_name = "clips.fitti.io" },
	{ pattern = "www.fitti.io/*/clip/*", zone_name = "www.fitti.io" }
]
